openapi: 3.0.0
info:
  title: agqr-radio-program-guide-api
  version: '1.0'
  description: |-
    **[非公式]  超A&G+ 番組表 API**  
    データ更新頻度: 1日ごと（JST 07:00 ごろ）

    何かバグ等ありましたら、Issue を立てていただくか下記の連絡先までご連絡ください。  
    Twitter(X): [@sun_yryr](https://twitter.com/sun_yryr)  
    GitHub: https://github.com/sun-yryr/agqr-program-guide
servers:
  - url: 'https://agqr.sun-yryr.com/api'
    description: production
  - url: 'http://localhost:8080/api'
    description: local
tags:
  - name: v1
    description: 'v1 API'
paths:
  /all:
    get:
      summary: 週刊番組表を取得
      tags: [v1]
      parameters:
        - name: isRepeat
          in: query
          description: true を指定すると再放送を含めた番組情報を返却する
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/old-program'
      operationId: get-all
      description: |-
        1週間分全ての番組情報を返却する。
        実行日の日本時間の0時から7日後の23時59分までの間の番組情報を返却する。
  /today:
    get:
      summary: 日間番組表を取得
      tags: [v1]
      parameters:
        - name: isRepeat
          in: query
          description: true を指定すると再放送を含めた番組情報を返却する
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/old-program'
      operationId: get-today
      description: |-
        本日放送予定の番組情報を返却する。
        本日とは、日本時間の0時から23時59分までの間のことを指す。
  /now:
    get:
      summary: 現在の番組情報を返却
      tags: [v1]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/old-program'
      operationId: get-now
      description: 現在放送中の番組情報を返却する
components:
  schemas:
    program:
      title: program
      type: object
      properties:
        id:
          type: integer
          description: 番組ごとに一位なID。再放送の場合も別のIDになる。
        title:
          type: string
          description: 番組タイトル
        info:
          type: string
          description: 番組の説明
        url:
          type: string
          description: 番組の詳細ページURL
        start_datetime:
          type: string
          format: date-time
          example: '2020-04-18T14:00:00Z'
          description: 番組開始時間
        end_datetime:
          type: string
          format: date-time
          example: '2020-04-18T14:30:00Z'
          description: 番組終了時間
        dur:
          type: integer
          description: 番組時間(分)
        is_repeat:
          type: boolean
          description: 再放送かどうか
        is_movie:
          type: boolean
          description: 動画付きかどうか
        is_live:
          type: boolean
          description: 生放送かどうか
        personalities:
          type: array
          description: 出演者
          items:
            $ref: '#/components/schemas/personality'
      required:
        - id
        - title
        - info
        - url
        - start_datetime
        - end_datetime
        - dur
        - is_repeat
        - is_movie
        - is_live
        - personalities
    old-program:
      title: old-program
      type: object
      properties:
        title:
          type: string
        ft:
          type: string
          format: date-time
          description: YmdHM の12桁
        to:
          type: string
          format: date-time
          description: YmdHM の12桁
        pfm:
          type: string
          description: 出演者。「、」区切り？
        dur:
          type: integer
          description: 番組時間(分)
        isBroadcast:
          type: boolean
          description: 配信しているか。基本的に常にtrueとなる。
        isRepeat:
          type: boolean
          description: 再放送かどうか
      required:
        - title
        - ft
        - to
        - pfm
        - dur
        - isBroadcast
    personality:
      title: personality
      type: object
      properties:
        id:
          type: string
          description: 出演者
        name:
          type: string
          description: 名前
        url:
          type: string
          description: 出演者の詳細ページURL
      required:
        - id
        - name
        - url
