name: buildtime-linux

on:
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt -q update
          sudo apt -q install wget libxml2-dev clang libicu-dev -y
      - name: Install swift
        run: |
          mkdir tmp && cd tmp
          wget https://swift.org/builds/swift-5.3.3-release/ubuntu2004/swift-5.3.3-RELEASE/swift-5.3.3-RELEASE-ubuntu20.04.tar.gz
          tar xvf swift-5.3.3-RELEASE-ubuntu20.04.tar.gz
          mv swift-5.3.3-RELEASE-ubuntu20.04/usr/ $HOME
          echo "$HOME/usr/bin" >> $GITHUB_PATH
      - run: swift package resolve
      - name: swift build
        run: swift build --enable-test-discovery -c release
