name: Deploy SwaggerUI

on:
  push:
    branches: [ master ]
    paths:
      - "reference/agqr-radio-program-guide-api.v2.yaml"
  pull_request:
    branches: [ develop ]
    paths:
      - "reference/agqr-radio-program-guide-api.v2.yaml"

jobs:
  swagger_validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate by openapitools/openapi-generator-cli
        run: |
          docker run --rm -v "$(pwd):/tmp" openapitools/openapi-generator-cli \
          validate -i /tmp/reference/agqr-radio-program-guide-api.v2.yaml
      - name: Validate by stoplight/spectral
        uses: stoplightio/spectral-action@v0.7.3
        with:
          file_glob: 'reference/agqr-radio-program-guide-api.v2.yaml'
          repo_token: ${{ github.token }}
          event_name: ${{ github.event_name }}

  swagger_deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Upload to S3
        env:
          S3_SWAGGER_BUCKET: ${{ secrets.S3_SWAGGER_BUCKET }}
        run: aws s3 cp ./reference/agqr-radio-program-guide-api.v2.yaml s3://$S3_SWAGGER_BUCKET/schema.yaml --quiet
