name: test

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift package resolve
      - name: swift test
        run: swift test
